# 公共配置文件
spring:
  application:
    name: chengBI-backEnd
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxx:3306/xxxx
    username: root
    password: xxxxxx
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: xxxxx
    port: 6380
    timeout: 5000
    password: xxxxx
    #配置MQ
  rabbitmq:
    host: xxxxx
    port: 5672
    password: xxxx
    username: xxxx
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  #配置MQ
#  rabbitmq:
#    host: 43.140.246.183
#    port: 5672
#    password: chengxiang
#    username: admin
server:
  port: 8107
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        domain: xxxxx
        same-site: lax
        secure: false
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: ""
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
#鱼聪明AI 接入
yuapi:
  client:
    access-key: xxxxxx
    secret-key: xxxxx
